spring.application.name=backend

# PostgreSQL database
spring.datasource.url=jdbc:postgresql://localhost:5432/soen345db
spring.datasource.username= username_placeholder
spring.datasource.password= password_placeholder

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect